---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - name: client-port-external
      protocol: TCP
      {{- if .Values.vault.enableTLS }}
      port: 443
      targetPort: {{ .Values.vault.listenerPort }}
      {{- else }}
      port: 80
      targetPort: {{ .Values.vault.listenerPort }}
      {{- end }}
    - name: cluster-port
      protocol: TCP
      port: {{ .Values.vault.clusterListenerPort }}
      {{- if .Values.vault.nodePort }}
      nodePort: {{ .Values.vault.nodePort }}
      {{- end }}
  selector:
    app: {{ template "vault.fullname" . }}
    release: {{ .Release.Name }}
