Vault:
  Image: "quay.io/samsung_cnct/vault"
  ImageTag: "0.8.3"
  ImagePullPolicy: "Always"
  Component: "vault"
  NodePort: 32443

# Consul backend example
#  Backend:
#    Type: "consul"
#    Address: "consul-consul:8500"
#    Token: "token"

# etcd backend example
  Backend:

    Type: "etcd"
    Address: "etcd-vault-etcd"
    Port: 3379
    Etcd_Api: "v3"
    Path: "vault/"
    Sync: "false"
    Username: ""
    Password: ""
    Scheme: "http"
    Token: "token"
    ClusterAddress: ""
    DisableClustering: "false"

  Replicas: 3
  Cpu: "512m"
  Memory: "200Mi"

#  Tls:
#    Cert: ""
#    Key: ""
#    Ca: ""
#

  tolerations:
   # - key: taintKey
   #   value: taintValue
   #   operator: Equal
   #   effect: NoSchedule
  scheduling:
    affinity:
      node:
        type: #requiredDuringSchedulingIgnoredDuringExecution
        labels:
        # - key: iamalabelkey
        #   operator: In
        #   values: ["value1", "value2"]

