vault:
  image: "quay.io/samsung_cnct/vault"
  imageTag: "0.8.3"
  imagePullPolicy: "Always"
  component: "vault"
  nodePort: 32443
  backend: etcd
  enableTLS: false
  enableDebug: true
  replicas: 3
  cpu: "512m"
  memory: "200Mi"


# Consul backend example
  consulBackend:
    address: "consul-consul:8500"
    token: "token"

# etcd backend example
  etcdBackend:
    discoverySRV:
    address: "etcd-vault-etcd"
    port: 2379
    etcdApi: "v3"
    path: "vault/"
    sync: "false"
    username: ""
    password: ""
    scheme: "http"
    token: "token"
    clusterAddress: ""
    disableClustering: "false"
    clientCA:
    clientCert:
    clientKey:

  init:
    key_masters:
      - email: "snafu.x@gmail.com"
        pubkey: "LS0tLS1CRUdJTiBQR1AgUFVCTElDIEtFWSBCTE9DSy0tLS0tCgptUUVOQkZvRTZkOEJDQURIOS9vWXU0SG82ZVNXR250aDZMMzIvRkQrdFljZVdnbzRSK0Ezc01mdFV2VmJka2FnCnRPNThCZ0E4U2JpaUJIczlGa1BoYkw0RVJIdzEwVkFMNHJ3bUlROStQUm85MXUraGVMN0VyWmg0VFZCSkZOQloKSzJmY1hETFgwV2hLVnhtUERNa1FkZzN2MTRITDVucnk4WllFODZSbjFLTzVUak94T1ZBSm10cGFWTU9YY3phUgpldDZYM29DRzZwWHBqb3diTlUxelZqR1JveElFRVNrMHBsbk9nQzJ1NjcvVFJEWElKSjZiQlhDWFhhRzJGSS84CllsTGhRL2R6MkpKK2ZmOGN3UUYyTDdHdlpQNm0xdU1IM08ybXpsSFZ2a3dNdUpEcXVvejdSdWxvK2xOczRmWnAKY21uNnNVVnQ3bk9VcWtMb1AwUUVzZGhPV095YXQ5MXVwOHhyQUJFQkFBRzBLVXBoYldWeklDaEthVzBwSUVFdQpJRU52Ym01bGNpQThjMjVoWm5VdWVFQm5iV0ZwYkM1amIyMCtpUUUzQkJNQkNBQWhCUUphQk9uZkFoc0RCUXNKCkNBY0NCaFVJQ1FvTEFnUVdBZ01CQWg0QkFoZUFBQW9KRUlmRWlrYWwxYkNEOVBjSUFMd25uaUpKaEJKUVUya1QKU0p3YkZCOS9hTDlRUWxGM3BXS2xqQ0xXRUx3aHFsMXhSM0VvRFlHYjcwdy9RRTVRNXRFa2JqVEIveGpXTTVoWQo1R2hYZ2pHSFFSUkVwa3FHUVpYSTJWaWZkRTJnaytjQVNJcjc0NHd2K1IvdHNjVlVkRmFNMWVKMGpNYndPOFpYClhlTWRPcUxzbnRCdWV5eXBnS0puckVnZDBzZ0g5bVpQK05mckFWLy9OUzQ4Y2JJejcrR215c0FvVEQwZys0V20KRTZRdzhIemdqMjZqV1NCU3o1bDFIbVlYQkMvcHhDdGdtSXAyVHRJSVJ0Tjgxbi9uREJZeU93SDVPb0RrdThBcApBQzFCS0Y2bk8zaWZoanl5OVlObHRuL25pMzY4TmlPeWpnbHZCNDVPYmEvenN6Z3J3eFh3VCtDNGFOMTFjRUxhCkE3NXRRU3k1QVEwRVdnVHAzd0VJQVBNcDlJSHpPSnBsZEZ6TnZjRnBkWWRSRXZpeUVjYmJjS1BHcGR1VnJvN0UKdVFXdzdjUVRQdFBZeEpzb05PbnZwY0dDemw0V2NRdGZlZFZSLzc3cFlvWk9uMWlnNUFGRUNUSzMyeEJEWVBDbgpGRlA5Ym5EMlNSSEk2N0ZmUERxRnRxb0tKamJDUUVDbVpNSXlaQzZWNkQyYko0Unc1SWtnNktBWEttMnY4alk3CmJVVXBBZEs0M2VSbDhocXAwSXVlMkRyd3kzbUQweUxoRC8vR2M2MUFLQUxFQkFCVmxCSzNtNmIvYVpUSldHeTMKaXBKVHhpYVJnMEdUT0tJdTl5czlnZUZRQXhSWFRjc2tTUVN1UnEwVzlxVmhYR0QrRVRxOFN5RWd3OXBhWTBGbwpvbmRMUWU4TCtKam9wOGtPRkJBdlc1Nk1nOVU3N3g3UStUSGgvNHlqTlJrQUVRRUFBWWtCSHdRWUFRZ0FDUVVDCldnVHAzd0liREFBS0NSQ0h4SXBHcGRXd2d6UDdCLzBSWlF3ZU9GdjdaSlJDZ2tvUVNSaWxuTU5pRlc5SHdseHcKd2RPVjVyVUExTEpOVXpnMy9OM2FqZTB6ellxZ293V1lNQUFUbXFEQjQvbWYyZWZMS3IwaUVodVFrRkFFQjB6NgpWREd3KzlIY2RDQnpNRk44ckJKQnpCR3BCNEFGOS80ekxoSnZiM2VuNzliWGFxMlhIUDlhM1Z1d0FVaFJuMnZsCkYxTk10akFrUDRlSzZ1ZUg4VUhCWCt4bERUV24vT0QzL0FhNlQyNys4RnRJaFByRUxsL2tTSHUyanpaV0dWVUgKRW1sNTlOaUZnWmVMSkFNZ0RrL0VvVTBYdGVXaDV2R1MwLy8yL0FEQzgraVR4WmxYMlZjRFJXeG4wVzNVU2NxZwp2L0xZQXV2aWRJUXp3OTlOWHNYQmtYd3Q5Qm5EdjdpdjdVbDRNNGdRSjFLNHpGNnByaTFMCj16RE1ECi0tLS0tRU5EIFBHUCBQVUJMSUMgS0VZIEJMT0NLLS0tLS0K"
      - email: "joejulian@gmail.com"
        pubkey: ""
      - email: "alika.larsen@gmail.com"
        publey: ""
    
# TLS info
  tls:
    cert: ""
    key: ""
    ca: ""

  tolerations:
   # - key: taintKey
   #   value: taintValue
   #   operator: Equal
   #   effect: NoSchedule
  scheduling:
    affinity:
      node:
        type: #requiredDuringSchedulingIgnoredDuringExecution
        labels:
        # - key: iamalabelkey
        #   operator: In
        #   values: ["value1", "value2"]

