---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.vault.component }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.vault.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "vault.fullname" . }}
    spec:
      containers:
      - name: {{ template "vault.fullname" . }}
        image: "{{.Values.vault.image}}:{{.Values.vault.imageTag}}"
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        imagePullPolicy: {{ .Values.vault.imagePullPolicy }}
        ports:
{{- if .Values.vault.enableTLS }}
        - name: https
          containerPort: 443
{{- else }}
        - name: http
          containerPort: 80
{{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/vault/cfg
        - name: config
          mountPath: /vault-bin/vault-start.sh
          subPath: vault-start.sh
          readOnly: false
{{- if .Values.vault.enableTLS }}
        - name: tls
          mountPath: /etc/vault/tls
{{- end }}
        env:
        - name: VAULT_DEBUG
          value: "{{.Values.vault.enableDebug}}"
        - name: RUN_TESTS
          value: "false"
        - name: VAULT_INIT_VARS
          value: "{
                    [
                      {{- range $i, $k := .Values.vault.init.key_masters }}
                      {{- if gt $i 0 }},{{ end }} 
                      {
                        "email": {{ $k.email | quote }}, 
                        "pubkey": {{ $k.pubkey | quote }} 
                      }
                      {{- end }}
                    ]
                  }"
        resources:
          limits:
            cpu: {{ .Values.vault.cpu }}
            memory: {{ .Values.vault.memory }}
          requests:
            cpu: {{ .Values.vault.cpu }}
            memory: {{ .Values.vault.memory }}
        command:
          - "/bin/sh"
          - "/vault-bin/vault-init.sh"
      volumes:
      - name: config
        configMap:
          name: {{ template "vault.fullname" . }}
          items:
          - key: config.json
            path: config.json
{{- if .Values.vault.enableTLS }}
      - name: tls
        secret:
          secretName: {{ template "vault.fullname" . }}.tls
{{- end }}
{{- if .Values.vault.tolerations }}
      tolerations:
      {{- range .Values.vault.tolerations }}
      - key: {{ .key | default ("") }}
        value: {{ .value | default ("")}}
        operator: {{ .operator | default ("Equal") }}
        effect: {{ .effect  | default ("")}}
      {{- end }}
{{- end }}
{{- if .Values.vault.scheduling.affinity }}
{{- if .Values.vault.scheduling.affinity.node }}
{{- if .Values.vault.scheduling.affinity.node.labels }}
      affinity:
        nodeAffinity:
          {{ .Values.vault.scheduling.affinity.node.type }}:
            nodeSelectorTerms:
            - matchExpressions:
                {{- range .Values.vault.scheduling.affinity.node.labels }}
                - key: {{ .key }}
                  operator: {{ .operator }}
                  values:
                  {{- range .values }}
                  - {{ . }}
                  {{- end }}
                {{- end }}
{{- end }}
{{- end }}
{{- end }}
