{{- if .Values.vault.enableTLS }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    app: {{ template "vault.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.vault.component }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  vault.crt: {{ .Values.tls.cert }}
  vault.key: {{ .Values.tls.key }}
  vault.ca: {{ .Values.tls.ca }}
{{- end}}
